---
deployment:
  tasks:
    - "export DEPLOYPATH=/home/ealindenssp/public_html/lizlinden.com"
    - "/bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --exclude 'node_modules' $cpanel_dir/ $DEPLOYPATH"
